---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: # give it a unique name
spec:
  deletionPolicy: Delete
  forProvider:
    acl: private
    locationConstraint: eu-central-1
  providerConfigRef:
    name: default
