apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bucket-composition
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XBucket
  resources:
    - name: bucket
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        metadata:
          name: # patched
        spec:
          forProvider:
            locationConstraint: eu-central-1
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
