---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.example.org
spec:
  group: example.org
  names:
    kind: XBucket
    plural: xbuckets
  claimNames:
    kind: Bucket
    plural: buckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        # Same as CRD schemas
        type: object
        properties:
          spec:
            type: object
            properties:
              providerConfigRef:
                type: object
                properties:
                  name:
                    type: string
                required:
                - name
            required:
            - providerConfigRef
